return {
  diagnostics_style = { italic = true },
  plugins = { -- enable or disable extra plugin highlighting
    aerial = true,
    beacon = false,
    bufferline = true,
    dashboard = true,
    highlighturl = true,
    hop = false,
    indent_blankline = true,
    lightspeed = false,
    ["neo-tree"] = true,
    notify = true,
    ["nvim-tree"] = false,
    ["nvim-web-devicons"] = true,
    rainbow = true,
    symbols_outline = false,
    telescope = false,
    vimwiki = false,
    ["which-key"] = true,
  },
}
